concurrent = 1
check_interval = 0

[[runners]]
  name = "zll"
  url = "https://gitlab.com/"
  token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ruby:2.1"
    privileged = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
